---
name: CI
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
      - name: 'Install'
        run: yarn install
      - name: 'Test'
        run: yarn test
      - name: 'Build'
        run: yarn build
      - name: 'Build Storybook'
        run: yarn build-storybook
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
      - name: 'Install'
        run: yarn install
      - name: 'Lint TypeScript'
        run: yarn lint:ts
      - name: 'Lint CSS'
        run: yarn lint:css
